name: build-and-push-docker-image

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  on-push-job:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4





